apiVersion: apps/v1
kind: Deployment
metadata:
  name: casbinrule-express-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casbinrule-express-demo
  template:
    metadata:
      labels:
        app: casbinrule-express-demo
    spec:
      containers:
        - name: casbinrule-express-demo
          image: g2ang/casbinrule-express-demo:latest
          ports:
            - containerPort: 3000
