apiVersion: apps/v1
kind: Deployment
metadata:
  name: casbinrule-express-demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: casbinrule-express-demo
  template:
    metadata:
      labels:
        app: casbinrule-express-demo
    spec:
      containers:
        - name: casbinrule-express-demo
          image: casbinrule-express-demo:v1
          ports:
            - containerPort: 3000
          env:
            - name: VERSION
              value: "v1"