apiVersion: v1
kind: Service
metadata:
  name: casbinrule-express-demo
spec:
  type: NodePort
  selector:
    app: casbinrule-express-demo
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080